name: "FAP: Build for Momentum mntm-011"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-fap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ufbt (Momentum release)
        id: build
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          app-dir: .
          sdk-index-url: https://up.momentum-fw.dev/firmware/directory.json
          sdk-channel: release   # atualmente aponta para mntm-011

      - name: Upload FAP
        uses: actions/upload-artifact@v4
        with:
          name: nfc_relay-${{ steps.build.outputs.suffix }}
          path: ${{ steps.build.outputs.fap-artifacts }}
